config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'test_javascripts#index'

  resources :conversations do
   resources :messages
  end
  
  resources :meetings do
    resources :comments, module: :meetings
  end
  resources :fb_messages
  resources :channel_users
  resources :channels do
    resource :channel_user
  end
  devise_for :users
  
  resources :posts do
    resource :like, module: 'posts'
    
    member do
      patch :publish
    end
  end

  get 'callback/index'
  post '/callback/index', to: 'callback#received_data'
  get 'callback/received_data'
  # root to: 'callback#index'


  mount Facebook::Messenger::Server, at: "bot"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/intersection_observers', to: 'test_javascripts#intersection_obs', as: 'intersection'
  get '/coming_soon', to: 'test_javascripts#coming_soon', as: 'coming_soon'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_rich_text :body
end

app/controllers/meetings/comments_controller.rb
class Meetings::CommentsController < CommentsController
  before_action :authenticate_user!
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Meeting.find(params[:meeting_id])
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = current_user.meetings.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    @comments = Comment.new
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meetings_path, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
        MeetingMailer.with(meeting: @meeting, user: current_user).meeting_mail.deliver_later
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_all_meetings.html.erb
<% meetings.each do |meeting| %>
  <div style="margin:2rem 0;">
    <div style="margin:1rem 0;">
      <%= link_to meeting.name, meeting %>
    </div>
    <div>
      <%= readable_time(meeting.start_time) %>
      <%= readable_time(meeting.end_time) %>
    </div>
    <div>
      <%= link_to "Cancel Meeting", meeting, method: :delete, data: { confirm: "Are you sure to delete this meeting?" } %>          
    </div>
  </div>
<% end %>

app/views/meetings/_calendar.html.erb
<%= month_calendar(events: meetings) do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, meeting_path(meeting) %>
    </div>
  <% end %>
<% end %>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col">
      <% unless current_user.meetings.any? %>
        <%= link_to 'New Meeting', new_meeting_path %>
      <% else %>
        <h1>Meetings</h1>
        <ul id="nav-tab" class="nav nav-pills nav-fill">
          <li class="nav-item">
            <%= link_to '#calendar', class: 'tab nav-link active' do %>
              Meeting Calendar
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to '#all-meetings', class: 'tab nav-link' do %>
              All Meetings
            <% end %>
          </li>
        </ul>
        <div id="all-meetings" class="tab-panel">
          <%= render partial: "all_meetings", locals: { meetings: @meetings } %>
        </div>

        <div id="calendar" class="tab-panel active" style="margin:2rem 0;">
          <h2>Meeting Calendar</h2>
          <div id="meeting-calendar">
            <%= render partial: "calendar", locals: { meetings: @meetings } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<% unless user_signed_in? %>
  <%= link_to "Login", new_user_session_path() %>
<% else %>
  <%#= render partial: "comments/form" %>
<% end %>

<div>
  <%= render partial: "comments/comments", locals: {commentable: @meeting} %>
  <%= render partial: "comments/form", locals: {commentable: @meeting} %>
</div>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>