config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'test_javascripts#index'

  resources :conversations do
   resources :messages
  end
  
  resources :meetings do
    resources :comments, module: :meetings
  end
  resources :fb_messages
  resources :channel_users
  resources :channels do
    resource :channel_user
  end
  devise_for :users
  
  resources :posts do
    resource :like, module: 'posts'
    
    member do
      patch :publish
    end
  end

  get 'callback/index'
  post '/callback/index', to: 'callback#received_data'
  get 'callback/received_data'
  # root to: 'callback#index'


  mount Facebook::Messenger::Server, at: "bot"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/intersection_observers', to: 'test_javascripts#intersection_obs', as: 'intersection'
  get '/coming_soon', to: 'test_javascripts#coming_soon', as: 'coming_soon'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/channel_user.rb
class ChannelUser < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/fb_message.rb
class FbMessage < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_rich_text :body
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :bigint           not null, primary key
#  title        :string
#  publish_date :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  published_at :datetime
#
class Post < ApplicationRecord
  has_many :likes
  has_many :users, through: :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_messageable

  has_many :likes
  has_many :posts, through: :likes
  has_many :channel_users, dependent: :destroy
  has_many :channels, through: :channel_users
  has_many :messages, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_many :comments, dependent: :destroy

  def likes?(post)
    post.likes.where(user_id: id).any?
  end
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
  protect_from_forgery with: :null_session
  require 'dino'

  def index
    if params["hub.verify_token"] == "asd"
      render json: params["hub.challenge"]
    end
  end

  def received_data
    therequest = request.body.read
    data = JSON.parse(therequest)
    parse_data(data)
    render "received_data"
  end

  def light_up_led text
    board = Dino::Board.new(Dino::TxRx.new)
    led = Dino::Components::Led.new(pin: 13, board: board)
    
    if text.include? "gay"
      led.send(:on)
      sleep 0.5
      led.send(:off)
      sleep 0.5
      led.send(:on)
      sleep 0.5
      led.send(:off)
    elsif text.include? "no"
      led.send(:on)
      sleep 0.5
      led.send(:off)
    else
      led.send(:on)
      sleep 0.5
      led.send(:off)
    end
  end

  def parse_data(data)
    enteries = data["entry"]
    enteries.each do |entry|
      entry["messaging"].each do |messaging|
        sender = messaging["sender"]["id"]
        text = messaging["message"]["text"]
        Rails.logger.info("+++++++++++++++++++++++++")
        Rails.logger.info(messaging)
        Rails.logger.info("+++++++++++++++++++++++++")
        # analysis(sender, text)
        myjson = {"recipient": {"id": "#{sender}"},"message": {"text": "#{text}\n\nTime is: #{Time.now.strftime('%I:%M:%S %p')}"}}
        puts HTTP.post(url, json: myjson)

        light_up_led(text)
      end
    end
  end

  def analysis(sender, text)
    message = FbMessage.where(:received => text).first
    if message
      reply = message.reply
    else
      reply = "Sorry not found"
    end
    send_message(sender,reply)
  end

  def send_message(sender, text)
    myjson = {"recipient": {"id": "#{sender}"},"message": {"text": "#{text}"}}
    puts HTTP.post(url, json: myjson)
  end

  def url
    "https://graph.facebook.com/v12.0/me/messages?access_token=x"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy publish]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @post.update(published_at: Time.zone.now)
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :publish_date)
    end
end

app/controllers/test_javascripts_controller.rb
class TestJavascriptsController < ApplicationController
  def intersection_obs
  end

  def index
  end

  def coming_soon
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_time(time)
    time.strftime("%b %d, %I:%M%P")
  end

  def author_of(record)
    user_signed_in? && current_user.id == record.user_id
  end

  def admin?
    user_signed_in? && current_user.admin?
  end
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/channel_users_helper.rb
module ChannelUsersHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fb_messages_helper.rb
module FbMessagesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/test_javascripts/coming_soon.html.erb
<%= video_tag "bg.mp4", playsinline: :playsinline, autoplay: :autoplay, loop: :loop, muted: :muted, class: "bg-video"%>
<!-- Masthead-->
<div class="masthead">
  <div class="masthead-content text-white">
    <div class="container-fluid px-4 px-lg-0">
      <h1 class="fst-italic lh-1 mb-4">Our Website is Coming Soon</h1>
      <p class="mb-5">We're working hard to finish the development of this site. Sign up below to receive updates and to be notified when we launch!</p>
      <form id="contactForm" data-sb-form-api-token="API_TOKEN">
        <!-- Email address input-->
        <div class="row input-group-newsletter">
          <div class="col"><input class="form-control" id="email" type="email" placeholder="Enter email address..." aria-label="Enter email address..." data-sb-validations="required,email" /></div>
          <div class="col-auto"><button class="btn btn-primary disabled" id="submitButton" type="submit">Notify Me!</button></div>
        </div>
        <div class="invalid-feedback mt-2" data-sb-feedback="email:required">An email is required.</div>
        <div class="invalid-feedback mt-2" data-sb-feedback="email:email">Email is not valid.</div>
        <!-- Submit success message-->
        <!---->
        <!-- This is what your users will see when the form-->
        <!-- has successfully submitted-->
        <div class="d-none" id="submitSuccessMessage">
          <div class="text-center mb-3 mt-2">
            <div class="fw-bolder">Form submission successful!</div>
            To activate this form, sign up at
            <br />
            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
          </div>
        </div>
        <!-- Submit error message-->
        <!---->
        <!-- This is what your users will see when there is-->
        <!-- an error submitting the form-->
        <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3 mt-2">Error sending message!</div></div>
      </form>
    </div>
  </div>
</div>
<div class="social-icons">
  <div class="d-flex flex-row flex-lg-column justify-content-center align-items-center h-100 mt-3 mt-lg-0">
    <a class="btn btn-dark m-3" href="#!"><i class="fab fa-twitter"></i></a>
    <a class="btn btn-dark m-3" href="#!"><i class="fab fa-facebook-f"></i></a>
    <a class="btn btn-dark m-3" href="#!"><i class="fab fa-instagram"></i></a>
  </div>
</div>

app/views/test_javascripts/index.html.erb
<div class="container welcome-container">
  <div class="row">
    <div class="col">
      <h1>Lab Rats</h1>
      <ul>
        <li>
          <p><%= link_to 'Intersection Observers', intersection_path %></p>
        </li>
        <li>
          <p><%= link_to 'Station 29 (Coming Soon)', coming_soon_path %></p>
        </li>
        <li>
          <p><%= link_to 'Posts', posts_path %></p>
        </li>
        <li>
          <p><%= link_to 'Realtime Group Chat', channels_path %></p>
        </li>
        <li>
          <p><%= link_to 'Conversations', conversations_path %></p>
        </li>
        <li>
          <p><%= link_to 'Facebook Messenger Bot Callback', callback_index_path %></p>
        </li>
        <li>
          <p><%= link_to 'Facebook Messenger Bot Messages', fb_messages_path %></p>
        </li>
        <li>
          <p><%= link_to 'Scheduling App', meetings_path %></p>
        </li>
      </ul>
    </div>
    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
  </div>
</div>

app/views/test_javascripts/intersection_obs.html.erb
<main>
  <section class="home-intro">
    <h1>Intersection Observer is pretty useful</h1>
  </section>

  <div class="home-about">
    <h2>About us</h2>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
    <div class="columns">
      <div class="col fade-in">
        <h3>Lorem, ipsum.</h3>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vitae
          maiores fuga eos provident voluptas perferendis.
        </p>
      </div>
      <div class="col fade-in">
        <h3>A, illo!</h3>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit.
          Voluptatibus minima quo beatae eius blanditiis officiis.
        </p>
      </div>
      <div class="col fade-in">
        <h3>Repudiandae, error?</h3>
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laborum
          quasi quis doloribus quia illum laudantium.
        </p>
      </div>
    </div>
  </div>

  <div class="home-more-stuff">
    <div class="more-stuff-grid">
    <%# Hello future me. Lazy load images with loading="lazy", make sure to specify width, and height! Also check if img.css max-width:100% and height:auto %>
    <%# Thank me later %>
      <img
        loading="lazy"
        src="https://unsplash.it/400"
        alt=""
        class="slide-in from-left"
        width="400"
        height="600"
      />
      <p class="slide-in from-right">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis fugit,
        quae beatae vero sit magni quaerat id ratione. Dolor optio unde amet
        omnis sapiente neque cumque consequuntur reiciendis deserunt.
        Dolorem vero exercitationem consequuntur, eligendi cupiditate
        debitis facilis quibusdam magni. Eveniet.
      </p>
    </div>
    <div class="more-stuff-grid">
      <p class="slide-in from-left">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis fugit,
        quae beatae vero sit magni quaerat id ratione. Dolor optio unde amet
        omnis sapiente neque cumque consequuntur reiciendis deserunt.
        Dolorem vero exercitationem consequuntur, eligendi cupiditate
        debitis facilis quibusdam magni. Eveniet.
      </p>
      <img
        loading="lazy"
        src="https://unsplash.it/401"
        alt=""
        class="slide-in from-right"
        width="400"
        height="600"
      />
    </div>
    <div class="more-stuff-grid">
      <img loading="lazy" src="//unsplash.it/400" alt="" class="slide-in from-left" width="400"
        height="600" />
      <p class="slide-in from-right">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis fugit,
        quae beatae vero sit magni quaerat id ratione. Dolor optio unde amet
        omnis sapiente neque cumque consequuntur reiciendis deserunt.
        Dolorem vero exercitationem consequuntur, eligendi cupiditate
        debitis facilis quibusdam magni. Eveniet.
      </p>
    </div>
    <div class="more-stuff-grid">
      <p class="slide-in from-left">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis fugit,
        quae beatae vero sit magni quaerat id ratione. Dolor optio unde amet
        omnis sapiente neque cumque consequuntur reiciendis deserunt.
        Dolorem vero exercitationem consequuntur, eligendi cupiditate
        debitis facilis quibusdam magni. Eveniet.
      </p>
      <img 
        loading="lazy"
        src="https://unsplash.it/401"
        alt=""
        class="slide-in from-right"
        width="400"
        height="600"
      />
    </div>
    <div class="more-stuff-grid">
      <img loading="lazy" src="//unsplash.it/400" alt="" class="slide-in from-left" width="400"
        height="600" />
      <p class="slide-in from-right">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis fugit,
        quae beatae vero sit magni quaerat id ratione. Dolor optio unde amet
        omnis sapiente neque cumque consequuntur reiciendis deserunt.
        Dolorem vero exercitationem consequuntur, eligendi cupiditate
        debitis facilis quibusdam magni. Eveniet.
      </p>
    </div>
    <div class="more-stuff-grid">
      <p class="slide-in from-left">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis fugit,
        quae beatae vero sit magni quaerat id ratione. Dolor optio unde amet
        omnis sapiente neque cumque consequuntur reiciendis deserunt.
        Dolorem vero exercitationem consequuntur, eligendi cupiditate
        debitis facilis quibusdam magni. Eveniet.
      </p>
      <img
        loading="lazy"
        src="https://unsplash.it/401"
        alt=""
        class="slide-in from-right"
        width="400"
        height="600"
      />
    </div>
  </div>
</main>